USE [master]
GO
/****** Object:  Database [Almacen]    Script Date: 27/11/2016 18:24:17 ******/
CREATE DATABASE [Almacen]
 CONTAINMENT = NONE
GO
ALTER DATABASE [Almacen] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Almacen].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Almacen] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Almacen] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Almacen] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Almacen] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Almacen] SET ARITHABORT OFF 
GO
ALTER DATABASE [Almacen] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Almacen] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Almacen] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Almacen] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Almacen] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Almacen] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Almacen] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Almacen] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Almacen] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Almacen] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Almacen] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Almacen] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Almacen] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Almacen] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Almacen] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Almacen] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Almacen] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Almacen] SET RECOVERY FULL 
GO
ALTER DATABASE [Almacen] SET  MULTI_USER 
GO
ALTER DATABASE [Almacen] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Almacen] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Almacen] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Almacen] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Almacen] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Almacen', N'ON'
GO
USE [Almacen]
GO
/****** Object:  Table [dbo].[categorias]    Script Date: 27/11/2016 18:24:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[categorias](
	[idCategoria] [int] IDENTITY(1,1) NOT NULL,
	[nombreCategoria] [varchar](50) NOT NULL,
 CONSTRAINT [PK_categorias] PRIMARY KEY CLUSTERED 
(
	[idCategoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO

Create Table productos(
	idCategoria int Not Null,
	idProducto int identity(1,1) Not Null,
	nombreProducto varchar(50),
	constraint PK_productos primary key (idProducto),
	constraint FK_categoriasproductos foreign key (idCategoria) references categorias(idCategoria) on update cascade on delete no action
	)



